export const SITE_CONFIG = {
  name: "Pixels Foto & Frame",
  description:
    "Professional photo printing, custom framing, and photo restoration services in Sandy, Utah since 2005.",
  url: "https://pixelsfoto.com",
  phone: "801-233-9090",
  phoneFormatted: "(801) 233-9090",
  email: "info@pixelsfoto.com",
  address: {
    street: "8934 S State",
    city: "Sandy",
    state: "UT",
    zip: "84070",
    full: "8934 S State, Sandy, UT 84070",
  },
  hours: {
    weekdays: "9:00 AM - 5:00 PM",
    saturday: "10:00 AM - 5:00 PM",
    sunday: "Closed",
  },
  social: {
    facebook: "https://facebook.com/pixelsfoto",
    instagram: "https://instagram.com/pixelsfoto",
  },
  established: 2005,
};

export const NAV_LINKS = [
  { href: "/services", label: "Services" },
  { href: "/contact", label: "Contact" },
] as const;

export const SERVICES = [
  {
    id: "printing",
    title: "Photo Printing",
    shortTitle: "Printing",
    description: "Professional quality prints from wallet size to large format posters.",
    icon: "printer",
    href: "/services/printing",
    popular: true,
  },
  {
    id: "custom-framing",
    title: "Custom Framing",
    shortTitle: "Framing",
    description: "Expert custom framing with hundreds of frame styles and mat options.",
    icon: "frame",
    href: "/services/custom-framing",
    popular: true,
  },
  {
    id: "art-reproduction",
    title: "Art Reproduction",
    shortTitle: "Art Repro",
    description: "High-quality reproductions of artwork and photographs.",
    icon: "palette",
    href: "/services/art-reproduction",
    popular: false,
  },
  {
    id: "jersey-framing",
    title: "Jersey Framing",
    shortTitle: "Jersey",
    description: "Shadow box framing for sports jerseys and memorabilia.",
    icon: "shirt",
    href: "/services/jersey-framing",
    popular: false,
  },
  {
    id: "photo-restoration",
    title: "Photo Restoration",
    shortTitle: "Restoration",
    description: "Restore and colorize damaged or faded photographs.",
    icon: "sparkles",
    href: "/services/photo-restoration",
    popular: true,
  },
  {
    id: "aluminum-prints",
    title: "Aluminum Prints",
    shortTitle: "Metal Prints",
    description: "Stunning metal prints with vibrant colors and modern appeal.",
    icon: "square",
    href: "/services/aluminum-prints",
    popular: false,
  },
  {
    id: "scanning",
    title: "Scanning Services",
    shortTitle: "Scanning",
    description: "Digitize slides, negatives, and old photographs.",
    icon: "scan",
    href: "/services/scanning",
    popular: false,
  },
  {
    id: "camera-rentals",
    title: "Camera Rentals",
    shortTitle: "Rentals",
    description: "Rent professional camera equipment for your next project.",
    icon: "camera",
    href: "/services/camera-rentals",
    popular: false,
  },
  {
    id: "video-transfer",
    title: "Video Transfer",
    shortTitle: "Video",
    description: "Convert VHS, film reels, and other formats to digital.",
    icon: "film",
    href: "/services/video-transfer",
    popular: false,
  },
] as const;
